language: python
sudo: required 
python:
  - "3.6"

services:
  - docker

install:
  - docker pull alephdata/ingestors
  - docker build --cache-from alephdata/ingestors -t alephdata/ingestors .

# command to run tests, e.g. python setup.py test
script:
  - make test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alephdata/ingestors
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      make dist ;
      twine upload dist/* ;
    fi
