# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 2.7

env: EXTRA_FIXTURES_PATH=~/ediscovery-files/assets

cache:
  - apt
  - pip
  - npm
  - directories:
    - ~/ediscovery-files

addons:
  apt:
    packages:
      - libtesseract-dev
      - imagemagick
      - poppler-utils
      - wkhtmltopdf
      - libreoffice
      - djvulibre-bin

before_install:
  - git clone --depth=1 https://gitlab.com/dzmitry-lahoda/ediscovery-files.git ~/ediscovery-files

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_dev.txt

# command to run tests, e.g. python setup.py test
script: make lint test
