dist: trusty
language: python
python:
  - "2.7"
  # - "3.6"

cache:
  - apt
  - pip

addons:
  apt:
    sources:
      - sourceline: 'ppa:libreoffice/ppa'
    packages:
      - libtesseract-dev
      - tesseract-ocr-eng
      - tesseract-ocr-osd
      - imagemagick
      - poppler-utils
      - libreoffice
      - djvulibre-bin
      - unzip
before_install:
  - pip install -U pip setuptools
  - sudo apt-get -qq update
  - sudo apt-get install -y readpst mdbtools libmagic1
  - wget --quiet -O /tmp/unrar.deb http://www.rarlab.com/rar/unrar_5.2.5-0.1_amd64.deb
  - sudo dpkg -i /tmp/unrar.deb
  # - sudo ln -s /usr/bin/python /usr/bin/python2.7.12
  # - wget --quiet -O /tmp/pst.tgz http://www.five-ten-sg.com/libpst/packages/libpst-0.6.70.tar.gz && cd /tmp && tar xvfz pst.tgz && cd libpst-0.6.70 && ./configure && make && make install


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -e .
  - pip install nose coveralls
  - pip install -r requirements_dev.txt

# command to run tests, e.g. python setup.py test
# script: make lint coverage
script:
  - nosetests -v --with-coverage --cover-package=ingestors

after_success:
  - coveralls
