version: "3.2"

services:
  postgres:
    image: postgres:10.0
    environment:
      POSTGRES_USER: ingest
      POSTGRES_PASSWORD: ingest
      POSTGRES_DATABASE: ingest

  redis:
    image: redis:alpine
    command: ["redis-server", "--save", "3600", "10"]

  convert-document:
    image: ghcr.io/alephdata/convert-document
    read_only: true
    restart: on-failure
    user: app
    tmpfs: /tmp

  ingest-file:
    build:
      context: .
      cache_from:
        - alephdata/ingest-file:latest
        - ghcr.io/alephdata/ingest-file:cache
    image: alephdata/ingest-file:${TAG:-latest}
    hostname: ingest
    tmpfs:
      - /tmp:mode=777
      - /data:mode=777
    environment:
      FTM_STORE_URI: postgresql://ingest:ingest@postgres/ingest
    volumes:
      - "./ingestors:/ingestors/ingestors"
      - "./tests:/ingestors/tests"
      - "./data:/ingestors/data"
      - "./requirements.txt:/ingestors/requirements.txt"
      - "~:/host"
    depends_on:
      - postgres
      - redis
      - convert-document
